name: Generate PDFs

on:
  push:
    branches:
      - master
      - dev
    # Run when markdown files or workflow itself are updated
    paths:
      - 'resume/markdown/*.md'
      - '.github/workflows/simplified_pdfs.yaml'

jobs:
  generate_pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Cache Pandoc and Weasyprint Dependencies
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/weasyprint  # Adjust this to the correct path for weasyprint and pandoc
        key: weasyprint-pandoc-dependencies-cache

    - name: Installing Dependencies (only if not cached)
      run: |
        sudo apt update
        sudo apt install -y weasyprint pandoc
        
    - name: Checking out repository (fetch the last 2 commits)
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch the latest two commits to allow diffing with HEAD^
    
    - name: Checking if resume/simplified directory is empty
      id: check_empty
      run: |
        if [ "$(ls -A resume/simplified | grep '\.md$')" ]; then
          echo "empty=false" >> $GITHUB_ENV
        else
          echo "empty=true" >> $GITHUB_ENV
        fi

    - name: Generating PDFs (only if resume/simplified is empty)
      run: |
        if [ "${{ env.empty }}" == "true" ]; then
          CHANGED_FILES=$(ls -A resume/markdown/*.md)
        else
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.resume/markdown/.*\.md$')
        fi
        for i in $CHANGED_FILES; do
          i=$(basename $i)
          echo "Processing $i"
          pandoc resume/markdown/$i -o "${i%.md}.html"
          weasyprint "${i%.md}.html" "resume/simplified/${i%.md}.pdf"
        done

    - name: Creating PR from dev to master
      uses: peter-evans/create-pull-request@v3
      with:
        title: Update resume
        commit-message: Update simplified resume PDFs
        add-paths: resume/markdown/*.md,resume/simplified/*.pdf
        body: |
          This PR updates the resume PDFs in the `resume/simplified` directory.
        branch: resume-workflow
        base: master
        labels: automated
        token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ github.actor }}
