name: Generate Simplified Resume PDFs from Markdown

on:
  push:
    branches:
      - master
    # Run when markdown files or workflow itself are updated
    paths:
      - 'resume/markdown/*.md'
      - '.github/workflows/simplified_pdfs.yaml'

jobs:
  process_markdown:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.get_changed.outputs.changed_files }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed markdown files
        id: get_changed
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^resume/markdown/.*\.md$' || true)
          echo "Changed files: $CHANGED_FILES"
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Replace <BIRTH_DATE> with age
        if: ${{ steps.get_changed.outputs.changed_files != '' }}
        run: |
          BIRTH_YEAR=2000
          BIRTH_MONTH=1
          BIRTH_DAY=3
          CURRENT_YEAR=$(date +%Y)
          CURRENT_MONTH=$(date +%-m)
          CURRENT_DAY=$(date +%-d)

          # Calculate age precisely
          AGE=$((CURRENT_YEAR - BIRTH_YEAR))
          if [ "$CURRENT_MONTH" -lt "$BIRTH_MONTH" ] || { [ "$CURRENT_MONTH" -eq "$BIRTH_MONTH" ] && [ "$CURRENT_DAY" -lt "$BIRTH_DAY" ]; }; then
            AGE=$((AGE - 1))
          fi

          echo "Calculated age: $AGE years"

          for file in ${{ steps.get_changed.outputs.changed_files }}; do
            echo "Updating $file"
            sed -i "s/<BIRTH_DATE>/$AGE/g" "$file"
          done

      - name: Replace <EXPERIENCE_YEARS> with experience years
        if: ${{ steps.get_changed.outputs.changed_files != '' }}
        run: |
          START_YEAR=2022
          START_MONTH=3
          CURRENT_YEAR=$(date +%Y)
          CURRENT_MONTH=$(date +%-m)
          TOTAL_MONTHS=$(( (CURRENT_YEAR - START_YEAR) * 12 + (CURRENT_MONTH - START_MONTH) ))
          EXPERIENCE_YEARS=$(echo "scale=1; $TOTAL_MONTHS / 12" | bc)

          echo "Calculated experience: $EXPERIENCE_YEARS years"

          for file in ${{ steps.get_changed.outputs.changed_files }}; do
            echo "Updating $file"
            sed -i "s/<EXPERIENCE_YEARS>/$EXPERIENCE_YEARS/g" "$file"
          done

      - name: Upload processed markdown files
        if: ${{ steps.get_changed.outputs.changed_files != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: processed-markdown
          path: ${{ steps.get_changed.outputs.changed_files }}

  generate_pdfs:
    runs-on: ubuntu-latest
    needs: process_markdown
    if: ${{ needs.process_markdown.outputs.changed_files != '' }}
    steps:
    - name: Checkout repository (fetch the last 2 commits)
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Download processed markdown files
      uses: actions/download-artifact@v4
      with:
        name: processed-markdown
        path: resume/markdown

    - name: Cache Pandoc and Weasyprint Dependencies
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/weasyprint
        key: weasyprint-pandoc-dependencies-cache

    - name: Installing Dependencies (only if not cached)
      run: |
        sudo apt update
        sudo apt install -y weasyprint pandoc

    - name: Checking if resume/simplified directory is empty
      id: check_empty
      run: |
        if [ "$(ls -A resume/simplified | grep '\.pdf$' || true)" ]; then
          echo "empty=false" >> $GITHUB_ENV
        else
          echo "empty=true" >> $GITHUB_ENV
        fi

    - name: Generating PDFs (only if resume/simplified is empty)
      run: |
        if [ "${{ env.empty }}" == "true" ]; then
          CHANGED_FILES=$(ls -A resume/markdown/*.md)
        else
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^resume/markdown/.*\.md$' || true)
        fi
        for i in $CHANGED_FILES; do
          BASE=$(basename "$i" .md)
          echo "Generating PDF for $BASE"
          pandoc "$i" -o "${BASE}.html"
          weasyprint "${BASE}.html" "resume/simplified/${BASE}.pdf"
        done

    - name: Creating PR from resume-workflow to master
      uses: peter-evans/create-pull-request@v3
      with:
        title: Update resume
        commit-message: Update simplified resume PDFs
        add-paths: resume/simplified/*.pdf
        body: |
          This PR updates the resume PDFs in the `resume/simplified` directory.
        branch: resume-workflow
        base: master
        labels: automated
        reviewers: ${{ github.actor }}
        token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ github.actor }}
